"""
schemas.py — the data shapes for this project.
"""

from typing import Literal, Optional
from pydantic import BaseModel, Field, model_validator


class BrandProfile(BaseModel):
    """A brand's profile information."""
    manufacturer_name: str
    manufacturer_address: str
    manufacturer_email: str
    responsible_person_name: Optional[str] = None
    responsible_person_address: Optional[str] = None
    responsible_person_email: Optional[str] = None


class ProductListing(BaseModel):
    title: str = Field(min_length=1)
    category: str
    price: float = Field(gt=0)
    gtin: str = Field(pattern=r"^\d{13}$")
    description: str = Field(min_length=1)
    product_specs: Optional[str] = None
    brand_profile: BrandProfile
    safety_warning_text: Optional[str] = None
    safety_document_url: Optional[str] = None
    declaration_of_conformity_url: Optional[str] = None
    ce_marking_present: bool
    disposal_instructions: Optional[str] = None
    image_url: str
    rating: Optional[float] = Field(default=None, ge=0, le=5)
    review_count: Optional[int] = None
    category_attributes: Optional[dict] = None
    model_number: Optional[str] = None   # "Type / number of model" — distinct from title
    country_of_origin: Optional[str] = None


class AuditResult(BaseModel):
    """The finished output of auditing one ProductListing.

    Scope note: this models an INTERNAL compliance audit verdict, not
    a government Safety Gate alert. Fields that require legal
    enforcement authority (measures ordered, dates of entry into
    force) are deliberately excluded — an audit tool can flag risk,
    it cannot issue a recall. See real Safety Gate alert
    OR/00113/26 for the full government-side report shape.
    """
    audit_id: str
    # output — internal tracking ID for this specific audit event,
    # generated by the calling pipeline code (not by this schema) when
    # the audit runs. Distinguishes a re-audit of the same listing (same
    # listing_gtin, new audit_id) from the original. Not a government
    # Safety Gate alert number.

    listing_gtin: str  # from input — identifies which ProductListing this audits

    verdict: Literal["compliant", "non_compliant", "escalated"]  # output

    risk_type: str
    # output — short category label (e.g. "Electric shock", "Choking
    # hazard"), set by the classifier/agent. Compulsory on every
    # AuditResult, including a "compliant" verdict — callers pass the
    # literal string "none" rather than omitting it, keeping this a
    # plain required field instead of Optional handling downstream.

    risk_score: float = Field(ge=0.0, le=1.0)  # output

    violations: list[str] = Field(default_factory=list)
    # output — simplified stand-in for real "legal provisions not
    # complied with" (e.g. citing the Low Voltage Directive, EN
    # 60335-1). Real standard-citation requires the RAG/hybrid-search
    # rule lookup tool — Phase 2. For now, plain-language violation
    # descriptions.

    pipeline_stage: Literal[
        "hygiene_check", "classifier", "investigator_agent", "reviewer_agent"
    ]  # output — which stage of the pipeline produced this verdict

    reasoning: str  # output — free-text explanation of the verdict

    # Deliberately NOT included, and why:
    # - alert_number, notifying_country: these identify a government
    #   Safety Gate filing; we don't file alerts, we produce internal
    #   audit verdicts
    # - measures_ordered, date_of_entry_into_force: legal enforcement
    #   actions are outside an audit tool's authority — out of scope
    #   by design, not a missing feature

    @model_validator(mode="after")
    def check_risk_type_matches_verdict(self) -> "AuditResult":
        if self.verdict == "compliant" and self.risk_type != "none":
            raise ValueError(
                'risk_type must be "none" when verdict is "compliant"'
            )
        if self.verdict != "compliant" and self.risk_type == "none":
            raise ValueError(
                'risk_type must not be "none" when verdict is '
                f'"{self.verdict}"'
            )
        return self